name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          HAS_SKIP: ${{contains(join(github.event.commits.*.message, '#SKIP'))}}
        run: echo "$COMMIT_MESSAGES"
        run: echo "$HAS_SKIP"